### ISSUE TITLE
PjArray>>reverse alters the object, whereas the Smalltalk implementation returns a copy

### ISSUE THREAD

**Issue by Ironirc** [PharoJS/PharoJS#66]
I have to say that the method name "reverse" seems to imply change of the receiver. 
https://www.gnu.org/software/smalltalk/manual-base/gst-base.html#Array confirms that reverse expects to make a copy. grrr... legacy.
We could add another method: #reversed ?

**Comment by dvmason** [comment]
We can't change #reverse, because it is standard Javascript and it would affect all JS code in the application, including JS libraries. In Pharo, #reverse and #reversed do the same thing (return a reversed copy). So yes, we'll add #reversed, and document that #reverse doesn't work the same as Smalltalk. We should also define #reversed for strings.

**Comment by dvmason** [comment]
Fixed, although we discovered a new obscure bug in the process, which will be logged against this issue
