### ISSUE TITLE
How to define an async function, create a promise, and await the promise

### ISSUE THREAD

**Issue by bouraqadi** [PharoJS/PharoJS#69]
We should also be able to tag methods as `async`, maybe using a pragma such as `<jsAsync>`.

We need to have a placeholder for JS Promise class in Pharo, so we can reference it. Ideally it should also be usable in Pharo world. This class should extend JS Promise with a method that allows making the `await` with JS code as:
```Smalltalk
await
   <javascript: 'return await this'>
```

**Comment by bouraqadi** [comment]
This issue is related to feature requests by multiple PharoJS users. An example, that hints an alternative way of approaching has been provided by @Ironirc:
> I'd like to do something like:
```Smalltalk
    self
        asyncDo: [ | result1 |
            result1 := self await: self promiseResult1.
            result2 := self await: (self promiseResult2WithResult1: result1)].
```

> But with the javascript pragma's, I can't figure out how to define methods:  asyncDo:  and await:
For `await` I tried:
```Smalltalk
await: promise
    <javascript: 'return await promise;'>
```
> But then js complains that keyword await is only allowed inside async functions.
> For the time being, I just chained some stuff like so:
`self promiseResult1 then: [:result1 | (self promiseResult2WithResult1: result1) then: [:res2 | do stuff...]]`

**Comment by bouraqadi** [comment]
Here's a possible implementation of the `asyncDo:` method.

```Smalltalk
asyncDo: aBlock
	<javascript: 'return (async function (){return aBlock();})();'>
```

**Comment by Ironirc** [comment]
How do you handle await?

**Comment by bouraqadi** [comment]
Indeed, `await` should be inside an `async` function. 
It is the sender's responsibility to should ensure the `Promise>>#await` message is  inside a block sent to `asyncDo:`.

**Comment by Ironirc** [comment]
```
async function doAsyncStuffInContainer(func) {
    return func();
}

function doAsyncStuffNow() {
    await Promise.resolve(1);
    console.log("we succeeded");
}

doAsyncStuffInContainer(doAsyncStuffNow)
```
Is this the js equivalent of what you mean?
Evaluating this also gives syntax error: _"Uncaught SyntaxError: await is only valid in async function"_

**Comment by bouraqadi** [comment]
Yes. I got the same error. We need to figure out another solution.

**Comment by Ironirc** [comment]
What would be the benefits?
After reading [Why JavaScript Async/Await Blows Promises Away](https://hackernoon.com/6-reasons-why-javascripts-async-await-blows-promises-away-tutorial-c7ec10518dd9) I'm not super convinced.
Readability appears to be less problematic in Smalltalk. There might be some advantages regarding error handling. (I'm not qualified to analyze this fully though)

Here and there I'm reading about an alternative implementation using JS generators.

**Comment by bouraqadi** [comment]
Right. Async/Await [bring too much problems](https://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/). We should avoid them as long as we can use the promises.

**Comment by dvmason** [comment]
I just spent 10 minutes searching for the article that @bouraqadi  linked to! :-) because it makes the strong case that this isn't the way you really want to do concurrent programming. But reading through that article again gives me some ideas about how we could do callbacks to Pharo BlockClosures from the JS side - as Promises. As @ironirc says, readability appears to be less problematic in Smalltalk.

Just an idea, but we could make callbacks to Pharo seamless by transpiling all BlockClosures to async functions and call with awaits (transitively!!!). It would be tricky, but might be worth an experiment. The problem would be that we then couldn't pass BlockClosures to JS libraries or system code (because they don't use await).

Alternately, if we made Pharo-side (i.e. proxied) `BlockClosure`s actually be `AsyncBlockClosure`s, it might work.

The idea is that `AsyncBlockClosure`s would not respond to `value`, `value`, etc., but required `awaitValue`, `awaitValue:`, etc. and recognized those as async, so the transpiler would insert `await` before the calls. Then we wouldn't have a way to make a method async, but they would become (transitive closure, again) async if they needed to be. And we could have a method `async` on `BlockClosure`s that turned them into `AsyncBlockClosure`s. Which we would "optimize" by creating the function as async.

So it *might* be worth it.
